### ISSUE TITLE
BUR change in xml 'div'

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-pywork#17]
At Caujole's suggestion, I made changes in the way the 'divisions' in Burnouf are displayed.
Small changes were made to:
* csl-pywork/v02/makotemplates/pywork/make_xml.py
* csl-websanlexicon/v02/makotemplates/web/webtc/basicdisplay.php
* csl-apidev/basicdisplay.php  (this file is identical to one above)

Here is an example showing the change to display of 'devana':
## Before the change

![bur_devana_old](https://user-images.githubusercontent.com/6393033/72297240-7c963800-3629-11ea-9f08-beec60003d34.PNG)

## After the change

![bur_devana_new](https://user-images.githubusercontent.com/6393033/72297276-8f107180-3629-11ea-949c-49cc4270ba1f.PNG)

**Comment by gasyoun** [comment]
>  I made changes in the way the 'divisions' in Burnouf are displayed.

Ok, so another nonbookish way of display, great.

**Comment by funderburkjim** [comment]
Another minor change at Caujole's suggestion:  no need for the '||' used by Burnouf text. The 
indentation is sufficient.

![image](https://user-images.githubusercontent.com/6393033/72366808-02b58b80-36c9-11ea-8f74-3c93bef27ac9.png)

**Comment by gasyoun** [comment]
> no need for the '||' used by Burnouf text.

Shoud not we document when we are not 1 to 1?
