### ISSUE TITLE
Progress

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-pywork#2]
There is now a functioning installer based on csl-orig, csl-websanlexicon, and csl-pywork repositories.

The best current documentation is in the readme.md for [csl-pywork/v02](https://github.com/sanskrit-lexicon/csl-pywork/tree/master/v02).

## Cologne B,L,A,M, D
These are now installed, using [csl-pywork/v02/redo_cologne_all.sh](https://github.com/sanskrit-lexicon/csl-pywork/blob/master/v02/redo_cologne_all.sh).
A typical url is https://www.sanskrit-lexicon.uni-koeln.de/scans/MWScan/2020/web/webtc/indexcaller.php.   This installation is for all dictionaries.

Currently, the apidev programs (including simple-search) are not yet linked to the new '2020' code.  

Currently, the sanskrit-lexicon home page does NOT link to the '2020' urls.

Request others to try some of the '2020' urls to be sure everything looks ok .  Check: 
* all of B,L,A,M,D with the '2020' urls for various dictionaries
* links to scanned images
* abbreviations (general and ls tooltips) for those dictionaries having such markup (mw, pw, pwg, bur, cae)
* mw links to westergaard and whitney for roots with such links.

When we've tested that the 2020 urls look good,  will transition other things to use
the 2020 urls, notably:
* sanskrit lexicon home page
* apidev (including simple-search)

The older (2013,2014) urls will still function -- they are unchanged, and I think they should be considered archival (e.g., not updated when digitizations in csl-orig are changed, as for error corrections.

## XAMPP B,L,A,M,D
The same code also works on XAMPP installation in Windows 10.
I've installed all dictionaries under XAMPP (after installing also sqlite3 and zip -- the v02 readme details one way to do this, as well as the Python2 version of mako module for template expansion). 

Suggest that someone else also do this installation on their XAMPP installation.

## TODO: Python3
The code has only been tested where 'python' means 'Python2'
I know there are still some programs that won't work when 'python' means 'Python3'.

## TODO: Ubuntu
There are some unresolved problems in installing in Ubuntu.  I'll mention some of these problems in a separate issue.

**Comment by funderburkjim** [comment]
## Request for testing 2020 urls at Cologne

@drdhaval2785 , @gasyoun , @artforlife  ---  request you
* look for differences in the sanskrit-lexicon 2020 urls and the older 2013, 2014 urls.  Please note differences via comments in this issue.
* try local xampp installation.  Things work on my machine, but maybe there will be differences on other machines.

We also need to test on Macintosh OS.  Maybe I can do that.  If other interested users have a Mac, they should see what is involved in trying the installations there.

**Comment by gasyoun** [comment]
> look for differences in the sanskrit-lexicon 2020 urls and the older 2013, 2014 urls.

If no bug where reported, the migration was brilliant.

**Comment by drdhaval2785** [comment]
Brilliant as usual for Jim
