### ISSUE TITLE
small change to xml for ap90

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-pywork#20]
This example occurred when examining the alternate headwords in AP90 of
pUlpalA.

The digitization (ap90.txt):
```
<L>19238.1<pc>0715-a<k1>pUpalA<k2>pUpalA(lI), pUpAlikA, pUpAlI
{#pUpalA(lI), pUpAlikA, pUpAlI, pU-#}¦
<>{#likA, pUpikA#}¦ A sort of sweet cake.
<LEND>
```

The (PRIOR) xml (ap90.xml) :
Note that `pUpalA(lI), pUpAlikA, pUpAlI, pU-` from the digitization is missing.
```
<H1><h><key1>pUpalA</key1><key2>pUpalA(lI), pUpAlikA, pUpAlI</key2></h>
<body><lb/>
<s>likA, pUpikA</s>  A sort of sweet cake.
</body>
<tail><L>19238.1</L><pc>0715-a</pc></tail></H1>
```

The (CHANGED) xml (ap90.xml):
Note that the missing text now present:
```
<H1><h><key1>pUpalA</key1><key2>pUpalA(lI), pUpAlikA, pUpAlI</key2></h>
<body>
<s>pUpalA(lI), pUpAlikA, pUpAlI, pU-</s>  <lb/><s>likA, pUpikA</s>  A sort of sweet cake.
</body>
<tail><L>19238.1</L><pc>0715-a</pc></tail></H1>
```

In cases like this (where there is useful information before the broken bar in
the digitization,  it is better to have that information in the display.

Hence, the change.

**Comment by gasyoun** [comment]
> In cases like this (where there is useful information before the broken bar in
the digitization, it is better to have that information in the display.

How many such cases where there?

**Comment by funderburkjim** [comment]
> How many cases ?

Don't know.
