### ISSUE TITLE
one.dtd: pe tag in pe dictionary

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-pywork#32]
We have recently introuced a 'pe' tag in the dtd for the dictionaries (person).
However,  'pe' is also the 'id' of the Puranic encyclopedia, and thus appears as the
root element of pe.xml.
This conflict was noticed by the xmllint validity checker used at Cologne.

Solution:
For the pe dictionary, do not use the 'pe' = person tag

**Comment by Andhrabharati** [comment]
How about renaming it as 'per' in all the works that have it??

**Comment by gasyoun** [comment]
> How about renaming it as 'per' in all the works that have it?

Makes sense. Otherwise a lot of mess just because a single dictionary.

**Comment by funderburkjim** [comment]
From [all_xmltags.txt](https://github.com/sanskrit-lexicon/COLOGNE/blob/master/xmltag/all_xmltags.txt), `<pe>` tag is used in dictionaries:
* gra Grassman
* md Macdonell

action to be done now: change `<pe>` tag to `<per>` in these, then modify one.dtd accordingly.

**Comment by funderburkjim** [comment]
Actions completed.

Note also added an 'issues' directory in csl-pywork.
Documentation of actions in [issue32/readme.txt](https://github.com/sanskrit-lexicon/csl-pywork/tree/master/issues/issue32/readme.txt).

This completes work regarding this issue.
