### ISSUE TITLE
Python3 compatibility in v02

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-pywork#4]
Let's devote this issue to all the Python programs in csl-pywork/v02.

A list of all these can be obtain by:
```
cd v02
find . -name '*.py'
```
These may occur either in
* v02 directory (2 files: generate.py and dictparms.py)
* makotemplates/pywork directory (7 files)
* distinctfiles/xxx/pywork directories  (make_xml.py occurs for all dictionaries xxx;
  a few additional files for dictionaries with abbreviations.

Some of the makotemplates versions have been converted to work in either Python2 or Python3 by @drdhaval2785 .

**Comment by funderburkjim** [comment]
## transcoding.py
This file currently only occurs in distinctfiles/mw/pywork/.
It is now Python2/3 compatible.
Also, it is now in sync with the version in [funderburkjim/sanskrit-transcoding repository](https://github.com/funderburkjim/sanskrit-transcoding/blob/master/transcoder.py).  And I think we should maintain this consistency.

**Comment by drdhaval2785** [comment]
@funderburkjim, Any python code in use out there which is not python2/3 compliant?

**Comment by funderburkjim** [comment]
All current production code in csl-pywork is python2/3 compatible, AFAIK.
