### ISSUE TITLE
make_xml.py a template

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-pywork#5]
In the previous revision of csl-pywork, make_xml.py was in 'distinctfiles'.  That is, when reconstructing a 2020 dictionary, csl-pywork used a separate version of the make_xml.py program for each dictionary.   Now, csl-pywork uses one [make_xml.py template](https://github.com/sanskrit-lexicon/csl-pywork/blob/master/v02/makotemplates/pywork/make_xml.py) to create the different versions.

This is an improvement, because now we can see all the variations in one place.   Also, we will be able to modify this template so that it generates code that is compatible with both python2 and python3  (Note the current template has not yet been modified for this compatibility.)

**Comment by funderburkjim** [comment]
All the 2020 dictionaries have been recreated using this template,  
Before doing this, a copy of the previous versions of the various xxx.xml  was saved (in scans/a_ejf/oldxml).
Then the dictionaries were recreated using the make_xml.py template and the various new xxx.xml compared to the previous.  And there were no *material* differences.

### Note on non-material differences
* Previously, there were 22 dictionaries with a small error in xxx.xml -- namely the broken vertical bar character (¦) of xxx.txt was mistakenly not removed by the distinct make_xml.py programs.  This error is now corrected.
* In vcp.xml, there is a small difference in 12 records, but this only involves where a space character appears in relation to an `<s>` tag. So is not material. For example:
  (under anurudDa, the two versions differ only between `</s>— <s> tri ` and `</s>—<s>  tri ` --- clearly not material differences.

**Comment by drdhaval2785** [comment]
Congratulations Jim. Now with more and more code being templated, we are moving towards the long coveted goal of unified code base at unprecedented speed.

Data and code both on github will help all contributors - correction submitters and code patch submitters.

**Comment by gasyoun** [comment]
It's a major milestone. Since August Jim has been working at double speed to get a barebone clear version of old code and architecture. Hope @YevgenJohn will be able to help soon enough.
