### ISSUE TITLE
csl-doc repository

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/csl-pywork#8]
Now we have csl-orig, csl-pywork and csl-websanlexicon as git based workflow to create updatable standalone local systems.
The only portion which is missing is the documentation part of it.
Now the documentation will also require some updates due to changed workflow.

I see csl-doc as a sibling of csl-orig etc.

Then everything, including documentation is also tackled via git.

**Comment by gasyoun** [comment]
> Then everything, including documentation is also tackled via git.

Agree. Because just yesterday @YevgenJohn spent four hours trying to understand where is the needed documentation.

**Comment by YevgenJohn** [comment]
Of course it's a learning curve, but absolutely, having everything in Git is needed for project to be self-contained and thus collaborative (everything needed to work on can be found there) and for DR purposes (local copy can be lost, once at GitHub always there, backed up by their resiliency). This also prevents the notorious problem of "junk-bin of different code versions" accumulating locally which is hard to isolate the currently-needed subset from. Apologies, my 2 cents.
